/**
 * Evaluation capsule assembly (specs/02 §12): a self-contained, immutable,
 * timestamp-free tree whose tar is byte-reproducible across builds. Layout:
 * flat pinned `node_modules/`, `runtime/` (install manifest + trusted boot
 * stub), `candidate/` (compiled bundle + manifests + patch), `runner/`
 * (offline probe through the real Cordis Loader), the composition overlay,
 * and identity documents (`manifest.json`, `provenance.json`, `sbom.spdx.json`,
 * `SHA256SUMS`).
 *
 * Digest wiring is acyclic by construction: `SHA256SUMS` covers the loadable
 * payload (everything except itself, `manifest.json` and `provenance.json`);
 * `manifest.json` and `provenance.json` cross-bind that digest; the build
 * manifest — outside the capsule — carries the capsule tar digest.
 * @module @dsh-evolve-le/core/builder/capsule
 */

import { createHash } from 'node:crypto'
import { chmod, cp, lstat, mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { gzipSync } from 'node:zlib'
import {
  buildCanonicalTar,
  type CanonicalFile,
  type CanonicalSource,
} from '../candidate/canonical.js'
import { computeTreeDigest } from '../digest.js'

import { BUILDER_VERSION } from '../version.js'

export const CAPSULE_PROTOCOL = 'dsh-evolve-le/capsule/v1'
export { BUILDER_VERSION }

/**
 * Capsule ACP entrypoint staged at the archive root (Gate 2, specs/01 §5.3,
 * runbook §2-3): Harbor's inline binary distribution launches `cmd`
 * (`./dsh-evolve-le-acp`) with the task workspace as cwd, so the wrapper
 * resolves its own directory — never the cwd — and execs the embedded runner
 * with an absolute config path. A task workspace cannot redirect which
 * composition boots. The interpreter is the capsule's own pinned runtime
 * (specs/02 §12): TB task images are per-task and almost none ship `node`,
 * so a PATH `node` here would kill every trial on those images before the
 * first ACP byte.
 */
export const ACP_ENTRYPOINT_NAME = 'dsh-evolve-le-acp'
export const ACP_ENTRYPOINT = [
  '#!/bin/sh',
  '# dsh-evolve-le capsule ACP entrypoint (Harbor inline binary distribution).',
  '# Resolves its own directory, never the task cwd, so the workspace cannot',
  '# redirect which composition boots (specs/01 §5.3). The interpreter is the',
  "# capsule's own pinned runtime (specs/02 §12) — never a PATH node.",
  'set -e',
  'DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)',
  'exec "$DIR/runtime/node" "$DIR/runner/bin/acp-boot.js" "$DIR/cordis.yml" "$@"',
  '',
].join('\n')

export interface CapsuleBundle {
  /** Deterministic tar over the candidate package content. */
  tar: Buffer
  tarSha256: string
  entrySha256: string
  fileCount: number
  bytes: number
}

/** Bundle = candidate metadata files + compiled `lib/` output. */
export async function buildBundle(
  source: CanonicalSource,
  compiledDir: string,
): Promise<{ bundle: CapsuleBundle; files: CanonicalFile[] }> {
  const metaPaths = new Set(['package.json', 'candidate.json', 'cordis.patch.yml'])
  const files: CanonicalFile[] = source.files
    .filter((file) => metaPaths.has(file.path))
    .map((file) => ({ ...file }))
  const compiled = await collectFiles(compiledDir, '')
  files.push(...compiled.map((file) => ({ ...file, path: `lib/${file.path}`, mode: 0o644 })))
  files.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0))

  const tar = buildCanonicalTar(files)
  const entry = files.find((file) => file.path === 'lib/index.js')
  if (entry === undefined) throw new Error('bundle entry lib/index.js missing after compile')
  return {
    bundle: {
      tar,
      tarSha256: sha256(tar),
      entrySha256: sha256(entry.content),
      fileCount: files.length,
      bytes: files.reduce((total, file) => total + file.content.length, 0),
    },
    files,
  }
}

/** Composition overlay booting the trusted stub plus the candidate plugin. */
export function bootConfig(
  candidatePackage: string,
  candidateId: string,
  mode: 'solve' | 'propose',
): string {
  return [
    '# Generated by the trusted builder (specs/02 §11 step 7/9):',
    '# trusted boot stub + packed candidate plugin, loaded through the real',
    '# Cordis Loader by runner/bin/probe.js. Never hand-edited.',
    '- id: system-prompt-stub',
    "  name: './runtime/system-prompt-stub.mjs'",
    '',
    '- id: self-evolving-candidate',
    `  name: '${candidatePackage}'`,
    '  config:',
    `    candidateId: ${candidateId}`,
    `    mode: ${mode}`,
    '',
  ].join('\n')
}

export interface InstallManifestEntry {
  name: string
  version: string
  digest: string
}

/**
 * Install the compiled candidate bundle into the flat closure at its declared
 * package name. The Cordis Loader resolves loader entries with a bare
 * `import(packageName)` from inside `node_modules/`, so the candidate must be
 * physically present there; `candidate/` keeps the canonical bundle copy and
 * both are written from the same `bundleFiles` list, so they cannot diverge.
 */
export async function installCandidateIntoClosure(
  nodeModulesDir: string,
  bundleFiles: CanonicalFile[],
  packageName: string,
): Promise<string> {
  const packageDir = join(nodeModulesDir, ...packageName.split('/'))
  await mkdir(packageDir, { recursive: true })
  for (const file of bundleFiles) {
    const at = file.path.lastIndexOf('/')
    if (at > 0) await mkdir(join(packageDir, file.path.slice(0, at)), { recursive: true })
    await writeFile(join(packageDir, file.path), file.content)
  }
  return packageDir
}

/** Per-package tree digests for the runtime closure (the "verified install manifest"). */
export async function buildInstallManifest(
  nodeModulesDir: string,
  packages: { name: string; version: string }[],
): Promise<{ text: string; sha256: string; entries: InstallManifestEntry[] }> {
  const entries: InstallManifestEntry[] = []
  for (const pkg of packages) {
    const { digest } = await computeTreeDigest(join(nodeModulesDir, ...pkg.name.split('/')))
    entries.push({ name: pkg.name, version: pkg.version, digest })
  }
  entries.sort((a, b) => (a.name < b.name ? -1 : 1))
  const document = {
    protocol: 'dsh-evolve-le/capsule-runtime/v1',
    algorithm: 'dsh-evolve-tree-v1',
    note: 'Flat pinned closure verified per package at admission; the capsule runner resolves these exact trees.',
    packages: entries,
  }
  const text = `${JSON.stringify(document, null, 2)}\n`
  return { text, sha256: sha256(Buffer.from(text, 'utf8')), entries }
}

/** Deterministic SPDX 2.3 SBOM; fixed epoch keeps double builds identical. */
export function buildSbom(options: {
  candidateId: string
  sourceDigest: string
  bundleSha256: string
  packages: InstallManifestEntry[]
}): string {
  const described = `SPDXRef-Package-candidate-${options.candidateId}`
  const packages = [
    {
      name: `dsh-evolve-le-candidate-${options.candidateId}`,
      SPDXID: described,
      versionInfo: options.candidateId,
      downloadLocation: 'NOASSERTION',
      filesAnalyzed: false,
      licenseConcluded: 'NOASSERTION',
      licenseDeclared: 'NOASSERTION',
      copyrightText: 'NOASSERTION',
      checksums: [
        { algorithm: 'SHA256', checksumValue: options.sourceDigest.replace(/^sha256:/, '') },
        { algorithm: 'SHA256', checksumValue: options.bundleSha256 },
      ],
    },
    ...options.packages.map((pkg) => ({
      name: pkg.name,
      SPDXID: `SPDXRef-Package-${pkg.name.replace(/[^A-Za-z0-9.-]/g, '-')}`,
      versionInfo: pkg.version,
      downloadLocation: 'NOASSERTION',
      filesAnalyzed: false,
      licenseConcluded: 'NOASSERTION',
      licenseDeclared: 'NOASSERTION',
      copyrightText: 'NOASSERTION',
    })),
  ]
  const document = {
    spdxVersion: 'SPDX-2.3',
    dataLicense: 'CC0-1.0',
    SPDXID: 'SPDXRef-DOCUMENT',
    name: `dsh-evolve-le-capsule-${options.candidateId}`,
    documentNamespace: `https://dsh-evolve-le.local/spdx/${options.candidateId}/${options.bundleSha256.slice(0, 16)}`,
    creationInfo: {
      created: '1970-01-01T00:00:00Z',
      creators: [`Tool: ${BUILDER_VERSION}`],
    },
    packages,
    relationships: [
      {
        spdxElementId: 'SPDXRef-DOCUMENT',
        relationshipType: 'DESCRIBES',
        relatedSpdxElement: described,
      },
      ...options.packages.map((pkg) => ({
        spdxElementId: described,
        relationshipType: 'DEPENDS_ON',
        relatedSpdxElement: `SPDXRef-Package-${pkg.name.replace(/[^A-Za-z0-9.-]/g, '-')}`,
      })),
    ],
  }
  return `${JSON.stringify(document, null, 2)}\n`
}

export interface CapsuleDocuments {
  capsuleManifest: Record<string, unknown>
  provenance: Record<string, unknown>
  installManifestSha256: string
  sbomSha256: string
  provenanceSha256: string
  sha256SumsDigest: string
  runnerDigest: string
}

/**
 * Assemble the full capsule tree at `capsuleDir` and return the identity
 * documents plus their digests. `sourceTreeDir` must already contain the
 * staged tree (with its `node_modules/` closure); `compiledDir` is the first
 * compile output.
 */
export async function assembleCapsule(options: {
  capsuleDir: string
  sourceTreeDir: string
  bundle: CapsuleBundle
  bundleFiles: CanonicalFile[]
  installManifest: { text: string; sha256: string; entries: InstallManifestEntry[] }
  candidatePackage: string
  candidateId: string
  sourceDigest: string
  toolchain: { node: string; pnpm: string; typescript: string }
  runnerSourceDir: string
  /** The pinned, digest-verified node binary embedded at runtime/node. */
  nodeRuntime: { path: string; sha256: string; version: string }
}): Promise<CapsuleDocuments> {
  const {
    capsuleDir,
    sourceTreeDir,
    bundle,
    bundleFiles,
    installManifest,
    candidatePackage,
    candidateId,
    sourceDigest,
    toolchain,
    runnerSourceDir,
    nodeRuntime,
  } = options
  await mkdir(capsuleDir, { recursive: true })

  // Flat pinned closure — copied per package from the verified install
  // manifest, so the capsule runtime is exactly the verified tree: no cache
  // droppings, no extra files a test run may have left in the staging area.
  await mkdir(join(capsuleDir, 'node_modules'), { recursive: true })
  for (const pkg of installManifest.entries) {
    await cp(
      join(sourceTreeDir, 'node_modules', ...pkg.name.split('/')),
      join(capsuleDir, 'node_modules', ...pkg.name.split('/')),
      { recursive: true, verbatimSymlinks: true },
    )
  }

  // runtime/: install manifest + trusted systemPrompt boot stub + the pinned
  // node interpreter the ACP entrypoint execs. The binary arrives
  // digest-verified from materializeNodeRuntime; the copy is verified again
  // so a drifted staging area fails closed instead of shipping silently.
  await mkdir(join(capsuleDir, 'runtime'), { recursive: true })
  await writeFile(join(capsuleDir, 'runtime/install-manifest.json'), installManifest.text, 'utf8')
  await cp(
    join(runnerSourceDir, 'probe/system-prompt-stub.js'),
    join(capsuleDir, 'runtime/system-prompt-stub.mjs'),
  )
  const runtimeNodePath = join(capsuleDir, 'runtime/node')
  await cp(nodeRuntime.path, runtimeNodePath)
  await chmod(runtimeNodePath, 0o755)
  const embeddedNodeSha256 = sha256(await readFile(runtimeNodePath))
  if (embeddedNodeSha256 !== nodeRuntime.sha256) {
    throw new Error(
      `capsule runtime/node: sha256 ${embeddedNodeSha256} != staged ${nodeRuntime.sha256}; the pinned runtime drifted mid-build`,
    )
  }

  // candidate/: metadata + compiled bundle.
  await mkdir(join(capsuleDir, 'candidate'), { recursive: true })
  for (const file of bundleFiles) {
    const at = file.path.lastIndexOf('/')
    if (at > 0)
      await mkdir(join(capsuleDir, 'candidate', file.path.slice(0, at)), { recursive: true })
    await writeFile(join(capsuleDir, 'candidate', file.path), file.content)
  }

  // runner/: ESM package + probe + ACP boot + boot/inventory compiled files.
  await mkdir(join(capsuleDir, 'runner/bin'), { recursive: true })
  await mkdir(join(capsuleDir, 'runner/cordis'), { recursive: true })
  await mkdir(join(capsuleDir, 'runner/acp'), { recursive: true })
  await writeFile(join(capsuleDir, 'runner/package.json'), '{"type":"module"}\n', 'utf8')
  await cp(join(runnerSourceDir, 'bin/candidate-probe.js'), join(capsuleDir, 'runner/bin/probe.js'))
  await cp(join(runnerSourceDir, 'bin/acp-boot.js'), join(capsuleDir, 'runner/bin/acp-boot.js'))
  await cp(join(runnerSourceDir, 'cordis/boot.js'), join(capsuleDir, 'runner/cordis/boot.js'))
  await cp(
    join(runnerSourceDir, 'cordis/inventory.js'),
    join(capsuleDir, 'runner/cordis/inventory.js'),
  )
  await cp(
    join(runnerSourceDir, 'acp/replay-agent.js'),
    join(capsuleDir, 'runner/acp/replay-agent.js'),
  )
  await cp(
    join(runnerSourceDir, 'acp/recorded-replay.js'),
    join(capsuleDir, 'runner/acp/recorded-replay.js'),
  )
  await cp(join(runnerSourceDir, 'version.js'), join(capsuleDir, 'runner/version.js'))
  const { digest: runnerDigest } = await computeTreeDigest(join(capsuleDir, 'runner'))

  // Composition overlay (solve mode is the resting state of the capsule).
  await writeFile(
    join(capsuleDir, 'cordis.yml'),
    bootConfig(candidatePackage, candidateId, 'solve'),
    'utf8',
  )

  // ACP entrypoint at the archive root: Harbor's inline binary registry entry
  // runs this after `tar -xf` into /opt/harbor-acp-agent/dist. Written before
  // collectFiles so SHA256SUMS covers it; the exec bit survives both the
  // canonical tar and Harbor's tar -xf.
  await writeFile(join(capsuleDir, ACP_ENTRYPOINT_NAME), ACP_ENTRYPOINT, 'utf8')
  await chmod(join(capsuleDir, ACP_ENTRYPOINT_NAME), 0o755)

  // Identity documents. SHA256SUMS covers the loadable payload only.
  const sbomText = buildSbom({
    candidateId,
    sourceDigest,
    bundleSha256: bundle.tarSha256,
    packages: installManifest.entries,
  })
  await writeFile(join(capsuleDir, 'sbom.spdx.json'), sbomText, 'utf8')

  const payloadFiles = await collectFiles(capsuleDir, '')
  const sumsLines = payloadFiles
    .filter(
      (file) =>
        file.path !== 'SHA256SUMS' &&
        file.path !== 'manifest.json' &&
        file.path !== 'provenance.json',
    )
    .map((file) => `${sha256(file.content)}  ${file.path}`)
    .sort((a, b) => (a.slice(64) < b.slice(64) ? -1 : 1))
  const sumsText = `${sumsLines.join('\n')}\n`
  await writeFile(join(capsuleDir, 'SHA256SUMS'), sumsText, 'utf8')
  const sha256SumsDigest = sha256(Buffer.from(sumsText, 'utf8'))

  const provenance = {
    protocol: CAPSULE_PROTOCOL,
    builder: BUILDER_VERSION,
    identity: { candidateId, sourceDigest },
    treeAlgorithm: 'dsh-evolve-tree-v1',
    sha256SumsDigest,
    bundleTarSha256: bundle.tarSha256,
    toolchain,
    nodeRuntime: { version: nodeRuntime.version, sha256: nodeRuntime.sha256 },
    note: 'Timestamp-free by construction; build time lives only in the out-of-capsule build manifest.',
  }
  const provenanceText = `${JSON.stringify(provenance, null, 2)}\n`
  await writeFile(join(capsuleDir, 'provenance.json'), provenanceText, 'utf8')

  // contents stats describe exactly the loadable payload SHA256SUMS covers.
  const payloadCovered = sumsLines.length
  const payloadBytes = payloadFiles
    .filter(
      (file) =>
        file.path !== 'SHA256SUMS' &&
        file.path !== 'manifest.json' &&
        file.path !== 'provenance.json',
    )
    .reduce((total, file) => total + file.content.length, 0)
  const capsuleManifest = {
    $schema: 'https://dsh-evolve-le.local/schemas/capsule.manifest.schema.json',
    schemaVersion: 1,
    protocol: CAPSULE_PROTOCOL,
    identity: { candidateId, sourceDigest },
    contents: {
      fileCount: payloadCovered,
      bytes: payloadBytes,
      sha256SumsDigest,
    },
    candidate: { digest: bundle.tarSha256, entry: 'lib/index.js' },
    runner: { digest: runnerDigest, entry: 'bin/probe.js' },
    runtime: {
      kind: 'install-manifest',
      digest: installManifest.sha256,
      detail:
        'Flat pinned Cordis closure verified per package in runtime/install-manifest.json; full DSH ACP closure staged at the Gate 1 container E2E.',
      nodeRuntime: {
        version: nodeRuntime.version,
        path: 'runtime/node',
        sha256: nodeRuntime.sha256,
      },
    },
    sbom: { path: 'sbom.spdx.json', sha256: sha256(Buffer.from(sbomText, 'utf8')) },
  }
  await writeFile(
    join(capsuleDir, 'manifest.json'),
    `${JSON.stringify(capsuleManifest, null, 2)}\n`,
    'utf8',
  )

  return {
    capsuleManifest,
    provenance,
    installManifestSha256: installManifest.sha256,
    sbomSha256: capsuleManifest.sbom.sha256,
    provenanceSha256: sha256(Buffer.from(provenanceText, 'utf8')),
    sha256SumsDigest,
    runnerDigest,
  }
}

/** Deterministic tar over the assembled capsule tree. */
export async function tarCapsule(capsuleDir: string): Promise<{
  tar: Buffer
  tarSha256: string
  fileCount: number
  bytes: number
}> {
  const files = await collectFiles(capsuleDir, '')
  const tar = buildCanonicalTar(files)
  return {
    tar,
    tarSha256: sha256(tar),
    fileCount: files.length,
    bytes: files.reduce((total, file) => total + file.content.length, 0),
  }
}

/**
 * Deterministic `.tar.gz` over the assembled capsule tree for Harbor's inline
 * ACP binary distribution (`archive` must be HTTPS + sha256; Harbor extracts
 * with `tar -xf` inside the task container). zlib deflate is deterministic for
 * a fixed level, so double builds must agree byte-for-byte — asserted by the
 * builder test suite. Level 6, not 9: the embedded node runtime makes the
 * payload ~120 MB, and level 9 costs ~2.6× the CPU for <1% size — a cost
 * every candidate build pays twice (the double-build proof).
 */
export async function archiveCapsule(capsuleDir: string): Promise<{
  tar: Buffer
  archive: Buffer
  archiveSha256: string
  tarSha256: string
  fileCount: number
  bytes: number
}> {
  const { tar, tarSha256, fileCount, bytes } = await tarCapsule(capsuleDir)
  const archive = gzipSync(tar, { level: 6 })
  return {
    tar,
    archive,
    archiveSha256: sha256(archive),
    tarSha256,
    fileCount,
    bytes,
  }
}

function sha256(content: Buffer): string {
  return createHash('sha256').update(content).digest('hex')
}

/** Read a tree into sorted canonical records (mode 0644/0755 by exec bit). */
async function collectFiles(root: string, prefix: string): Promise<CanonicalFile[]> {
  const out: CanonicalFile[] = []
  const dir = prefix === '' ? root : join(root, prefix)
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const rel = prefix === '' ? entry.name : `${prefix}/${entry.name}`
    if (entry.isDirectory()) {
      out.push(...(await collectFiles(root, rel)))
    } else if (entry.isFile()) {
      const stats = await lstat(join(dir, entry.name))
      out.push({
        path: rel,
        mode: (stats.mode & 0o111) !== 0 ? 0o755 : 0o644,
        content: await readFile(join(root, rel)),
      })
    }
  }
  return out.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0))
}

/** The compile output directory that ships as the candidate bundle. */
export function compiledBundleDir(workRoot: string): string {
  return join(workRoot, 'compile-1')
}
